Repository AztecGameLab/LongTermGame6, pull requests merged in 2022-01, with the labels that each got.

#8 Base enemy with some animations
  Assets/3D Assets/Enemies/Animations.meta
  Assets/3D Assets/Enemies/Animations/Standing Melee Attack Downward.fbx
  Assets/3D Assets/Enemies/Animations/Standing Melee Attack Downward.fbx.meta
  Assets/3D Assets/Enemies/Animations/Standing Melee Attack Horizontal.fbx
  Assets/3D Assets/Enemies/Animations/Standing Melee Attack Horizontal.fbx.meta
  Assets/3D Assets/Enemies/Animations/Standing Run Forward.fbx
  Assets/3D Assets/Enemies/Animations/Standing Run Forward.fbx.meta
  Assets/3D Assets/Enemies/Animations/Standing Turn Right 90.fbx
  Assets/3D Assets/Enemies/Animations/Standing Turn Right 90.fbx.meta
  Assets/3D Assets/Enemies/Animations/Standing Walk Right.fbx
  Assets/3D Assets/Enemies/Animations/Standing Walk Right.fbx.meta
  Assets/3D Assets/Enemies/Animations/Unarmed Idle Looking Ver. 1.fbx
  Assets/3D Assets/Enemies/Animations/Unarmed Idle Looking Ver. 1.fbx.meta
  Assets/3D Assets/Enemies/Animations/Unarmed Idle.fbx
  Assets/3D Assets/Enemies/Animations/Unarmed Idle.fbx.meta
  Assets/3D Assets/Enemies/Animations/Unarmed Run Forward.fbx
  Assets/3D Assets/Enemies/Animations/Unarmed Run Forward.fbx.meta
  Assets/3D Assets/Enemies/Animations/Unarmed Turn Left 90.fbx
  Assets/3D Assets/Enemies/Animations/Unarmed Turn Left 90.fbx.meta
  Assets/3D Assets/Enemies/Models.meta
  Assets/3D Assets/Enemies/Models/Enemy_No_1_Prelim.fbx
  Assets/3D Assets/Enemies/Models/Enemy_No_1_Prelim.fbx.meta
Labels: Art

#12 GitHub tutorial example
  Assets/Github Tutorial Assets/Dummy text.txt
  Assets/Github Tutorial Assets/Name Sign Up.txt
Labels: documentation

#29 Stool For Gallows
  Assets/3D Assets/World Assets/Stool.meta
  Assets/3D Assets/World Assets/Stool/Stool.fbx
  Assets/3D Assets/World Assets/Stool/Stool.fbx.meta
  Assets/3D Assets/World Assets/Stool/Stool_Mat.mat
  Assets/3D Assets/World Assets/Stool/Stool_Mat.mat.meta
  Assets/3D Assets/World Assets/Stool/Stool_Material_AlbedoTransparency_sRGB.png
  Assets/3D Assets/World Assets/Stool/Stool_Material_AlbedoTransparency_sRGB.png.meta
  Assets/3D Assets/World Assets/Stool/Stool_Material_MetallicSmoothness_Raw.png
  Assets/3D Assets/World Assets/Stool/Stool_Material_MetallicSmoothness_Raw.png.meta
  Assets/3D Assets/World Assets/Stool/Stool_Material_Normal_Raw.png
  Assets/3D Assets/World Assets/Stool/Stool_Material_Normal_Raw.png.meta
  Assets/Scenes/LizStreetLevelCpy.unity
Labels: Art

#38 Added my own sign up sheet
  Assets/Github Tutorial Assets/Liz Sign Up.txt
Labels: documentation

#40 Added my own sign up sheet
  Assets/Github Tutorial Assets/Nate Text .txt
Labels: documentation

#39 Added Github Signup
  Assets/Github Tutorial Assets/.DS_Store
  Assets/Github Tutorial Assets/Graham Sign Up.txt
  Assets/Github Tutorial Assets/Name Sign Up.txt
Labels: documentation

#45 Bri Text
  Assets/Github Tutorial Assets/Bri Text.txt
Labels: documentation

#49 Esther branch
  Assets/Github Tutorial Assets/Esther Sign Up.txt
Labels: documentation

#59 Adding Dead Bodies + Prefabs
  Assets/3D Assets/Dead Things.meta
  Assets/3D Assets/Dead Things/Burn victim pose.fbx
  Assets/3D Assets/Dead Things/Burn victim pose.fbx.meta
  Assets/3D Assets/Dead Things/Dead twitch.fbx
  Assets/3D Assets/Dead Things/Dead twitch.fbx.meta
  Assets/3D Assets/Dead Things/DeadMan01.fbx
  Assets/3D Assets/Dead Things/DeadMan01.fbx.meta
  Assets/3D Assets/Dead Things/Dead_Overgallows.fbx
  Assets/3D Assets/Dead Things/Dead_Overgallows.fbx.meta
  Assets/3D Assets/Dead Things/Falling Flat Impact.fbx
  Assets/3D Assets/Dead Things/Falling Flat Impact.fbx.meta
  Assets/3D Assets/Dead Things/Hangins_ArmsUp.fbx
  Assets/3D Assets/Dead Things/Hangins_ArmsUp.fbx.meta
  Assets/3D Assets/Dead Things/deadman01WithClothes-Tpose.fbx
  Assets/3D Assets/Dead Things/deadman01WithClothes-Tpose.fbx.meta
  Assets/3D Assets/Dead Things/deadman01WithClothes.fbx
  Assets/3D Assets/Dead Things/deadman01WithClothes.fbx.meta
  Assets/Prefabs/3D Assets/World Assets/Gallows_With_Bodies.prefab
  Assets/Prefabs/3D Assets/World Assets/Gallows_With_Bodies.prefab.meta
  Assets/Prefabs/3D Assets/World Assets/Stool.prefab
  Assets/Prefabs/3D Assets/World Assets/Stool.prefab.meta
  Assets/Scenes/LizStreetLevelCpy.unity
Labels: Art

#103 Inserted a lot of assets and finished the Tower area
  Assets/3D Assets/Modular Assets/Level 1/Textures/Wall_01/Materials.meta
  Assets/3D Assets/Modular Assets/Level 1/Textures/Wall_01/Materials/Wall_01_Window_01_Glass_AlbedoTransparency_sRGB.mat
  Assets/3D Assets/Modular Assets/Level 1/Textures/Wall_01/Materials/Wall_01_Window_01_Glass_AlbedoTransparency_sRGB.mat.meta
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Prefabs/3D Assets/Modular Assets/Chimney_01.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Chimney_01.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/House_Addon_Overhead.prefab
  Assets/Prefabs/3D Assets/Modular Assets/House_Addon_Overhead.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/House_Side_AddOn_Roof.prefab
  Assets/Prefabs/3D Assets/Modular Assets/House_Side_AddOn_Roof.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Overhang_Roof_supports.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Overhang_Roof_supports.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Roof_Large_Overhang.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Roof_Large_Overhang.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Roof_Small.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Roof_Small.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Small_Circular_Window.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Small_Circular_Window.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Wall_01.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Wall_01.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Wall_02.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Wall_02.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Wall_03.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Wall_03.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Wall_04.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Wall_04.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Wall_Large_for_addOn_01.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Wall_Large_for_addOn_01.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Wall_Small_for_addOn_01.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Wall_Small_for_addOn_01.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/Wall_X_Decor.prefab
  Assets/Prefabs/3D Assets/Modular Assets/Wall_X_Decor.prefab.meta
  Assets/Prefabs/3D Assets/Modular Assets/door_wooden_01.prefab
  Assets/Prefabs/3D Assets/Modular Assets/door_wooden_01.prefab.meta
  Assets/Prefabs/3D Assets/World Assets/Foundation_L.prefab
  Assets/Prefabs/3D Assets/World Assets/Foundation_L.prefab.meta
  Assets/Scenes/StreetLevel.unity
  Assets/Scenes/StreetLevel/LightingData.asset
  Assets/Scenes/StreetLevel/Lightmap-0_comp_dir.png
  Assets/Scenes/StreetLevel/Lightmap-0_comp_light.exr
  Assets/Scenes/StreetLevel/Lightmap-1_comp_dir.png
  Assets/Scenes/StreetLevel/Lightmap-1_comp_light.exr
  Assets/Scenes/StreetLevel/NavMesh.asset
  Assets/Settings/Lighting Settings/Fast Lighting.lighting
Labels: Programming, Level Design

#118 Create beautiful market stalls godly.png
  Assets/2D Assets/Dummy Concept Art/beautiful market stalls godly.png
Labels: Art

#95 Pig Pen Concept Art
  Assets/2D Assets/Concept_Art/Pig_pen_conceptArt.jpg
Labels: Art
